spring.application.name=flowable

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Show SQL statements in the console
spring.jpa.show-sql=true

# Execute custom sql scripts on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Flowable configuration show logging
#logging.level.org.flowable=DEBUG
#logging.level.org.flowable.engine.impl.persistence.entity=DEBUG
#logging.level.org.flowable.engine.impl.agenda=DEBUG
#logging.level.org.flowable.engine.impl.cmd=DEBUG
